name: CI
on: push
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: yarn install
      - name: Check if project is formatted
        run: npx kestrel format
      - name: Typecheck the project
        run: npx kestrel check
      - name: Run unit tests
        run: npx kestrel run TestMain
      - name: Check docs.json
        run: npx kestrel docs check
      - name: Run integration tests
        run: node integration/Task.test.mjs
